#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newcode?serverTimezone=GMT
    password: root
    username: root
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
#    mail
  mail:
    host: smtp.sina.com
    port: 465
    username: tjr1819324794@sina.com
    password: b604e35b4201aff1
    protocol: smtps
    properties.mail.smtp.ssl.enable: true
    #redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      group-id: test-consumer-group
#thymeleaf缓存关闭
#视图解析器
#    prefix: /templates/
#    suffix: .html
#配置别名
mybatis:
  type-aliases-package: com.example.community.domain
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
#设置日志级别
logging:
  level:
    root: info
#配置端口和网站名
server:
  port: 8080
  servlet:
    context-path: /community
community.path.domain: http://localhost:8080
community.path.upload: D:/1-TJR/course-java/project/community/community/src/main/resources/user


